### ISSUE TITLE
Generating 404 with CI 4.1.4

### ISSUE THREAD

**Issue by tangix** [SDPM-lab/Codeigniter4-Roadrunner#18]
Hi,
just tested your library and RoadRunner but found out it has problems with CI 4.1.4 and generates 404 pages after all initial workers have been accessed.
Downgrading to CI 4.1.1 and all works well.
Is this a known issue and where should I start looking to find a solution?

**Comment by monkenWu** [comment]
Hi, because Roadrunner's Runner opens Codeigniter4 in CLI mode. However, there is a [known issue]((https://github.com/codeigniter4/CodeIgniter4/issues/4843)) in version `4.1.4` that causes Route parsing to fail.

I'm not sure if this bug is fixed in the latest `4.1.5`, but you can try putting the following code into `public/index.php` and this function will make your route work correctly.

```php
function is_cli(): bool
{
    if (PHP_SAPI === 'cli')
    {
        return true;
    }

    if (defined('STDIN'))
    {
        return true;
    }

    if (! isset($_SERVER['REMOTE_ADDR'], $_SERVER['HTTP_USER_AGENT']) && isset($_SERVER['argv']) && count($_SERVER['argv']) > 0)
    {
        return true;
    }

    // if source of request is from CLI, the `$_SERVER` array will not populate this key
    return ! isset($_SERVER['REQUEST_METHOD']);
}
```
